export const USER_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER'
}

export const SHOP_TYPES = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE'
}